### PR TITLE
Don't enable search

### PR DESCRIPTION
**Pull request by mglaman**
Let's not enable the Search module since we push people towards Search API.

### CODE REVIEW

**Comment by jameswilson** [comment]
`./commerce_base/config/install/block.block.bartik_search.yml`, requires `search` module, might have to remove that as well.

**Comment by jameswilson** [comment]
Yup. confirmed... cant install, due to the bartik_search block.

```
Drupal\Core\Config\UnmetDependenciesException: Configuration objects (block.block.bartik_search) provided by commerce_base have unmet     [error]
dependencies in web/core/lib/Drupal/Core/Config/UnmetDependenciesException.php:84
Stack trace:
#0 web/core/lib/Drupal/Core/Config/ConfigInstaller.php(460):
Drupal\Core\Config\UnmetDependenciesException::create('commerce_base', Array)
#1 web/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php(132):
Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module', 'commerce_base')
#2 web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(141):
Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall('module', 'commerce_base')
#3 web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83):
Drupal\Core\Extension\ModuleInstaller->install(Array, false)
#4 web/core/includes/install.core.inc(1547): Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array,
false)
#5 web/core/includes/install.core.inc(652): install_install_profile(Array)
#6 web/core/includes/install.core.inc(530): install_run_task(Array, Array)
#7 web/core/includes/install.core.inc(115): install_run_tasks(Array)
#8 vendor/drush/drush/includes/drush.inc(726): install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#9 vendor/drush/drush/includes/drush.inc(711): drush_call_user_func_array('install_drupal', Array)
#10 vendor/drush/drush/commands/core/drupal/site_install.inc(80): drush_op('install_drupal',
Object(Composer\Autoload\ClassLoader), Array)
#11 vendor/drush/drush/commands/core/site_install.drush.inc(247):
drush_core_site_install_version('commerce_base', Array)
#12 vendor/drush/drush/includes/command.inc(366): drush_core_site_install('commerce_base')
#13 vendor/drush/drush/includes/command.inc(217): _drush_invoke_hooks(Array, Array)
#14 vendor/drush/drush/includes/command.inc(185): drush_command('commerce_base')
#15 vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#16 vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#17 vendor/drush/drush/drush.php(12): drush_main()
#18 {main}
```

**Comment by jameswilson** [comment]
This PR came about because of how we're leveraging commerce_base profile in a project. We install the site with commerce_base install profile via `drupal site:install` (the search module is installed) but then later in the install script, we sync the codebase with our exported config folder, where the search module is not enabled.   Somehow this gets things into an inconstent state where _something_ is requesting a route provided by the search module, but since the search module is no longer enabled, we're getting an error that prevents the load of any page.

**Comment by jameswilson** [comment]
I can confirm that removing the search module dependency and removing the file: `./commerce_base/config/install/block.block.bartik_search.yml`  does indeed solve the problem.

**Comment by jameswilson** [comment]
@citlacom, this is the issue we discussed today.

**Comment by mglaman** [comment]
@bojanz ping; maybe we could use this to also drop in `search_api` instead

**Comment by bojanz** [comment]
Sure, let's do that

**Pull request closed without merging**
